# Generated by Django 4.2.4 on 2023-10-19 17:47

from django.db import migrations
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', posts.models.UserCustomManager()),
            ],
        ),
    ]
